- name: maj 1
  hosts: all
  tasks:
        - name: Update sur les serveurs !
          apt: update_cache=yes force_apt_get=yes cache_valid_time=3600
        - name: Upgrade sur les serveurs !
          apt: upgrade=dist force_apt_get=yes
